import React, { useEffect, useMemo, useState } from 'react';
import { BarChart3, BriefcaseBusiness, CheckCircle2, Clock3, Download, Euro, FileJson, LayoutDashboard, Menu, Pencil, Plus, Search, Trash2, Users, X } from 'lucide-react';

const STATUSES=['Actief','On hold','Afgerond'];
const seedProjects=[
 {id:'p1',code:'PRJ-001',name:'ERP implementatie',client:'Demo klant',status:'Actief',budgetHours:240,hourlyRate:120,startDate:'2026-09-01',endDate:'2026-12-18',description:'Implementatie en procesbegeleiding'},
 {id:'p2',code:'PRJ-002',name:'Procesoptimalisatie',client:'Interne organisatie',status:'Actief',budgetHours:80,hourlyRate:110,startDate:'2026-09-05',endDate:'2026-10-31',description:'Analyse en verbeterplan'}
];
const seedEmployees=[
 {id:'e1',name:'Alex Pullens',email:'alex@apuconsultancy.nl',active:true},
 {id:'e2',name:'Demo Medewerker',email:'medewerker@example.nl',active:true}
];
const seedEntries=[
 {id:'t1',projectId:'p1',employee:'Alex Pullens',date:'2026-09-07',startTime:'08:30',endTime:'16:30',hours:8,activity:'Projectmanagement',description:'Planning en statusoverleg',billable:true,invoiced:false},
 {id:'t2',projectId:'p2',employee:'Alex Pullens',date:'2026-09-08',startTime:'09:00',endTime:'12:00',hours:3,activity:'Analyse',description:'Procesanalyse',billable:true,invoiced:false}
];
const today=()=>new Date().toISOString().slice(0,10);
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const money=v=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(v||0);
const hours=v=>`${Number(v||0).toLocaleString('nl-NL',{maximumFractionDigits:2})} uur`;
const date=v=>v?new Intl.DateTimeFormat('nl-NL').format(new Date(`${v}T12:00:00`)):'-';
const duration=(a,b)=>{if(!a||!b)return 0;const [ah,am]=a.split(':').map(Number),[bh,bm]=b.split(':').map(Number);const m=bh*60+bm-(ah*60+am);return m>0?Math.round(m/60*100)/100:0};
const weekStart=value=>{const d=new Date(`${value}T12:00:00`),day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);d.setHours(0,0,0,0);return d};
const sameWeek=(value,offset=0)=>{if(!value)return false;const target=weekStart(value),current=weekStart(today());current.setDate(current.getDate()+offset*7);return target.getTime()===current.getTime()};
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
const Button=({children,className='',...props})=><button className={`btn ${className}`} {...props}>{children}</button>;
const Field=({label,children})=><label className="field"><span>{label}</span>{children}</label>;

function Modal({title,onClose,children}){return <div className="overlay"><div className="modal"><header><h2>{title}</h2><Button className="icon secondary" onClick={onClose}><X size={18}/></Button></header><div className="modalbody">{children}</div></div></div>}
function ProjectForm({initial,onSave,onCancel}){const [d,setD]=useState(initial||{code:'',name:'',client:'',status:'Actief',budgetHours:0,hourlyRate:0,startDate:today(),endDate:'',description:''});const set=(k,v)=>setD(x=>({...x,[k]:v}));return <form onSubmit={e=>{e.preventDefault();onSave({...d,budgetHours:Number(d.budgetHours),hourlyRate:Number(d.hourlyRate)})}}><div className="formgrid"><Field label="Projectcode *"><input required value={d.code} onChange={e=>set('code',e.target.value)}/></Field><Field label="Status"><select value={d.status} onChange={e=>set('status',e.target.value)}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></Field></div><Field label="Projectnaam *"><input required value={d.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="Klant *"><input required value={d.client} onChange={e=>set('client',e.target.value)}/></Field><div className="formgrid"><Field label="Budgeturen"><input type="number" min="0" step=".25" value={d.budgetHours} onChange={e=>set('budgetHours',e.target.value)}/></Field><Field label="Uurtarief"><input type="number" min="0" step=".01" value={d.hourlyRate} onChange={e=>set('hourlyRate',e.target.value)}/></Field><Field label="Startdatum"><input type="date" value={d.startDate} onChange={e=>set('startDate',e.target.value)}/></Field><Field label="Einddatum"><input type="date" value={d.endDate} onChange={e=>set('endDate',e.target.value)}/></Field></div><Field label="Omschrijving"><textarea value={d.description} onChange={e=>set('description',e.target.value)}/></Field><div className="actions"><Button type="button" className="secondary" onClick={onCancel}>Annuleren</Button><Button type="submit">Project opslaan</Button></div></form>}
function EmployeeForm({initial,onSave,onCancel}){const [d,setD]=useState(initial||{name:'',email:'',active:true});return <form onSubmit={e=>{e.preventDefault();if(!d.name.trim())return;onSave({...d,name:d.name.trim(),email:d.email.trim()})}}><Field label="Naam *"><input required value={d.name} onChange={e=>setD({...d,name:e.target.value})}/></Field><Field label="E-mailadres"><input type="email" value={d.email} onChange={e=>setD({...d,email:e.target.value})}/></Field><label className="check"><input type="checkbox" checked={d.active} onChange={e=>setD({...d,active:e.target.checked})}/> Actieve medewerker</label><div className="actions"><Button type="button" className="secondary" onClick={onCancel}>Annuleren</Button><Button type="submit">Medewerker opslaan</Button></div></form>}
function TimeForm({projects,employees,initial,onSave,onCancel}){const [d,setD]=useState(initial||{projectId:projects[0]?.id||'',employee:employees.find(e=>e.active)?.name||'',date:today(),startTime:'08:30',endTime:'17:00',hours:8.5,activity:'Werkzaamheden',description:'',billable:true});const [error,setError]=useState('');const set=(k,v)=>setD(x=>{const n={...x,[k]:v};if(k==='startTime'||k==='endTime')n.hours=duration(n.startTime,n.endTime);return n});return <form onSubmit={e=>{e.preventDefault();const h=duration(d.startTime,d.endTime);if(!d.employee.trim()){setError('Vul de medewerker in.');return}if(h<=0){setError('De tot-tijd moet later zijn dan de van-tijd.');return}onSave({...d,employee:d.employee.trim(),hours:h})}}><Field label="Project *"><select required value={d.projectId} onChange={e=>set('projectId',e.target.value)}>{projects.filter(p=>p.status!=='Afgerond'||p.id===d.projectId).map(p=><option key={p.id} value={p.id}>{p.code} - {p.name}</option>)}</select></Field><Field label="Medewerker *"><select required value={d.employee} onChange={e=>set('employee',e.target.value)}><option value="">Selecteer een medewerker</option>{employees.filter(e=>e.active||e.name===d.employee).map(e=><option key={e.id} value={e.name}>{e.name}{!e.active?' (inactief)':''}</option>)}</select></Field><Field label="Datum *"><input required type="date" value={d.date} onChange={e=>set('date',e.target.value)}/></Field><div className="formgrid three"><Field label="Van *"><input required type="time" value={d.startTime} onChange={e=>set('startTime',e.target.value)}/></Field><Field label="Tot *"><input required type="time" value={d.endTime} onChange={e=>set('endTime',e.target.value)}/></Field><Field label="Berekende uren"><div className="calculated">{hours(d.hours)}</div></Field></div><Field label="Activiteit"><input value={d.activity} onChange={e=>set('activity',e.target.value)}/></Field><Field label="Omschrijving"><textarea value={d.description} onChange={e=>set('description',e.target.value)}/></Field><label className="check"><input type="checkbox" checked={d.billable} onChange={e=>set('billable',e.target.checked)}/> Factureerbare uren</label>{error&&<p className="error">{error}</p>}<div className="actions"><Button type="button" className="secondary" onClick={onCancel}>Annuleren</Button><Button type="submit">Uren opslaan</Button></div></form>}

export default function App(){
 const [projects,setProjects]=useState(()=>load('ph-projects-v3',seedProjects));const [employees,setEmployees]=useState(()=>load('ph-employees-v1',seedEmployees));const [entries,setEntries]=useState(()=>load('ph-entries-v3',seedEntries));const [view,setView]=useState('dashboard');const [employeeEdit,setEmployeeEdit]=useState(null);const [employeeOpen,setEmployeeOpen]=useState(false);const [mobile,setMobile]=useState(false);const [projectEdit,setProjectEdit]=useState(null);const [timeEdit,setTimeEdit]=useState(null);const [projectOpen,setProjectOpen]=useState(false);const [timeOpen,setTimeOpen]=useState(false);const [search,setSearch]=useState('');const [status,setStatus]=useState('Alle');const [toast,setToast]=useState('');const [invoiceSelected,setInvoiceSelected]=useState([]);const [invoiceDate,setInvoiceDate]=useState(today());const [invoiceReference,setInvoiceReference]=useState('');
 useEffect(()=>localStorage.setItem('ph-projects-v3',JSON.stringify(projects)),[projects]);useEffect(()=>localStorage.setItem('ph-employees-v1',JSON.stringify(employees)),[employees]);useEffect(()=>localStorage.setItem('ph-entries-v3',JSON.stringify(entries)),[entries]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(t)},[toast]);
 const byId=useMemo(()=>Object.fromEntries(projects.map(p=>[p.id,p])),[projects]);const byProject=useMemo(()=>entries.reduce((a,e)=>({...a,[e.projectId]:(a[e.projectId]||0)+Number(e.hours)}),{}),[entries]);const total=entries.reduce((s,e)=>s+Number(e.hours),0);const budget=projects.reduce((s,p)=>s+Number(p.budgetHours),0);const value=entries.reduce((s,e)=>s+(e.billable?e.hours*(byId[e.projectId]?.hourlyRate||0):0),0);const unbilled=entries.filter(e=>e.billable&&!e.invoiced);const invoiceMetric=(invoiced,offset)=>{const list=entries.filter(e=>e.billable&&Boolean(e.invoiced)===invoiced&&sameWeek(e.date,offset));return {hours:list.reduce((a,e)=>a+Number(e.hours),0),value:list.reduce((a,e)=>a+Number(e.hours)*(byId[e.projectId]?.hourlyRate||0),0)}};const unbilledThis=invoiceMetric(false,0),unbilledLast=invoiceMetric(false,-1),billedThis=invoiceMetric(true,0),billedLast=invoiceMetric(true,-1);const rows=[...entries].filter(e=>`${e.employee} ${e.activity} ${e.description} ${byId[e.projectId]?.name}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>`${b.date}${b.startTime}`.localeCompare(`${a.date}${a.startTime}`));const filteredProjects=projects.filter(p=>(status==='Alle'||p.status===status)&&`${p.code} ${p.name} ${p.client}`.toLowerCase().includes(search.toLowerCase()));
 const runInvoice=()=>{if(!invoiceSelected.length){setToast('Selecteer minimaal een urenregel');return}setEntries(x=>x.map(e=>invoiceSelected.includes(e.id)?{...e,invoiced:true,invoiceDate,invoiceReference:invoiceReference.trim()}:e));setInvoiceSelected([]);setInvoiceReference('');setToast('Geselecteerde uren zijn gefactureerd')};const saveEmployee=d=>{setEmployees(x=>employeeEdit?x.map(e=>e.id===employeeEdit.id?{...d,id:e.id}:e):[...x,{...d,id:uid('e')}]);setEmployeeOpen(false);setEmployeeEdit(null);setToast('Medewerker opgeslagen')};const saveProject=d=>{setProjects(x=>projectEdit?x.map(p=>p.id===projectEdit.id?{...d,id:p.id}:p):[...x,{...d,id:uid('p')}]);setProjectOpen(false);setProjectEdit(null);setToast('Project opgeslagen')};const saveEntry=d=>{setEntries(x=>timeEdit?x.map(e=>e.id===timeEdit.id?{...d,id:e.id}:e):[...x,{...d,id:uid('t')}]);setTimeOpen(false);setTimeEdit(null);setToast('Uren opgeslagen')};
 const download=(name,text,type)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)};const exportCsv=()=>{const data=[['Datum','Van','Tot','Medewerker','Projectcode','Project','Klant','Activiteit','Omschrijving','Uren','Factureerbaar','Gefactureerd','Factuurdatum','Factuurreferentie','Uurtarief','Waarde'],...entries.map(e=>{const p=byId[e.projectId]||{};return[e.date,e.startTime,e.endTime,e.employee,p.code,p.name,p.client,e.activity,e.description,e.hours,e.billable?'Ja':'Nee',e.invoiced?'Ja':'Nee',e.invoiceDate||'',e.invoiceReference||'',p.hourlyRate,e.billable?e.hours*p.hourlyRate:0]})];download('urenregistratie.csv','\ufeff'+data.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n'),'text/csv;charset=utf-8')};
 const nav=[['dashboard','Dashboard',LayoutDashboard],['projects','Projecten',BriefcaseBusiness],['employees','Medewerkers',Users],['hours','Urenregistratie',Clock3],['invoicing','Facturatie',Euro],['reports','Rapportage',BarChart3]];
 return <div className="app"><aside className={mobile?'open':''}><div className="brand"><Clock3/><div><b>Projecturen</b><small>Beheer & registratie</small></div><Button className="icon navclose" onClick={()=>setMobile(false)}><X/></Button></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>{setView(id);setSearch('');setMobile(false)}}><Icon size={19}/>{label}</button>)}</nav></aside><main><header className="top"><Button className="icon secondary menubtn" onClick={()=>setMobile(true)}><Menu/></Button><div><h1>{nav.find(n=>n[0]===view)?.[1]}</h1><p>Projecten, medewerkers en uren in een overzicht</p></div><Button onClick={()=>{setTimeEdit(null);setTimeOpen(true)}} disabled={!projects.length}><Plus size={17}/> Uren schrijven</Button></header><section className="content">
 {view==='dashboard'&&<><div className="metrics"><Metric label="Niet gefactureerd totaal" value={hours(unbilled.reduce((a,e)=>a+Number(e.hours),0))} sub={money(unbilled.reduce((a,e)=>a+Number(e.hours)*(byId[e.projectId]?.hourlyRate||0),0))} icon={<Euro/>}/><Metric label="Niet gefactureerd deze week" value={hours(unbilledThis.hours)} sub={money(unbilledThis.value)} icon={<Clock3/>}/><Metric label="Niet gefactureerd vorige week" value={hours(unbilledLast.hours)} sub={money(unbilledLast.value)} icon={<Clock3/>}/><Metric label="Gefactureerd deze week" value={hours(billedThis.hours)} sub={money(billedThis.value)} icon={<CheckCircle2/>}/><Metric label="Gefactureerd vorige week" value={hours(billedLast.hours)} sub={money(billedLast.value)} icon={<CheckCircle2/>}/></div><div className="card"><div className="reporthead"><div><h2>Nog te factureren uren</h2><p>Alle factureerbare uren die nog niet als gefactureerd zijn gemarkeerd</p></div><Button onClick={()=>setView('invoicing')}><Euro size={17}/> Facturatieproces openen</Button></div>{unbilled.slice(0,8).map(e=><div className="recent" key={e.id}><div><b>{byId[e.projectId]?.name}</b><small>{e.employee} · {e.activity}</small></div><span>{date(e.date)} · {e.startTime}-{e.endTime}</span><strong>{hours(e.hours)}</strong></div>)}</div></>}
 {view==='projects'&&<><Toolbar search={search} setSearch={setSearch}><select value={status} onChange={e=>setStatus(e.target.value)}><option>Alle</option>{STATUSES.map(s=><option key={s}>{s}</option>)}</select><Button onClick={()=>{setProjectEdit(null);setProjectOpen(true)}}><Plus size={17}/> Nieuw project</Button></Toolbar><div className="projectgrid">{filteredProjects.map(p=>{const used=byProject[p.id]||0,pct=p.budgetHours?Math.min(100,used/p.budgetHours*100):0;return <div className="card project" key={p.id}><div className="projecthead"><div><small>{p.code}</small><h2>{p.name}</h2><p>{p.client}</p></div><span className={`badge ${p.status.replace(' ','').toLowerCase()}`}>{p.status}</span></div><p>{p.description}</p><div className="progresslabel"><span>{hours(used)} besteed</span><span>{Math.round(pct)}%</span></div><div className="progress"><i style={{width:`${pct}%`}}/></div><div className="actions"><Button className="icon secondary" onClick={()=>{setProjectEdit(p);setProjectOpen(true)}}><Pencil size={17}/></Button><Button className="icon danger" onClick={()=>{if(entries.some(e=>e.projectId===p.id)){setToast('Verwijder eerst de uren op dit project');return}setProjects(x=>x.filter(a=>a.id!==p.id))}}><Trash2 size={17}/></Button></div></div>})}</div></>}

 {view==='employees'&&<><Toolbar search={search} setSearch={setSearch}><Button onClick={()=>{setEmployeeEdit(null);setEmployeeOpen(true)}}><Plus size={17}/> Nieuwe medewerker</Button></Toolbar><div className="employeegrid">{employees.filter(e=>`${e.name} ${e.email}`.toLowerCase().includes(search.toLowerCase())).map(e=>{const booked=entries.filter(x=>x.employee===e.name).reduce((a,x)=>a+Number(x.hours),0);return <div className="card employeeCard" key={e.id}><div className="projecthead"><div><h2>{e.name}</h2><p>{e.email||'Geen e-mailadres'}</p></div><span className={`badge ${e.active?'actief':''}`}>{e.active?'Actief':'Inactief'}</span></div><p>{hours(booked)} geregistreerd</p><div className="actions"><Button className="icon secondary" onClick={()=>{setEmployeeEdit(e);setEmployeeOpen(true)}}><Pencil size={17}/></Button><Button className="icon danger" onClick={()=>{if(entries.some(x=>x.employee===e.name)){setToast('Medewerker heeft uren en kan niet worden verwijderd');return}setEmployees(x=>x.filter(a=>a.id!==e.id))}}><Trash2 size={17}/></Button></div></div>})}</div></>}
 {view==='hours'&&<><Toolbar search={search} setSearch={setSearch}><Button onClick={()=>{setTimeEdit(null);setTimeOpen(true)}}><Plus size={17}/> Nieuwe boeking</Button></Toolbar><div className="tablewrap"><table><thead><tr>{['Datum','Van-tot','Medewerker','Project','Activiteit','Omschrijving','Uren','Factuurstatus','Waarde',''].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(e=>{const p=byId[e.projectId];return <tr key={e.id}><td>{date(e.date)}</td><td>{e.startTime}-{e.endTime}</td><td><b>{e.employee}</b></td><td>{p?.name}</td><td>{e.activity}</td><td>{e.description||'-'}</td><td><b>{hours(e.hours)}</b></td><td><span className={`badge ${e.invoiced?'actief':''}`}>{e.invoiced?'Gefactureerd':e.billable?'Open':'Niet factureerbaar'}</span></td><td>{e.billable?money(e.hours*(p?.hourlyRate||0)):'Niet factureerbaar'}</td><td><div className="rowactions"><Button className="icon secondary" onClick={()=>{setTimeEdit(e);setTimeOpen(true)}}><Pencil size={16}/></Button><Button className="icon danger" onClick={()=>setEntries(x=>x.filter(a=>a.id!==e.id))}><Trash2 size={16}/></Button></div></td></tr>})}</tbody></table></div></>}
 {view==='invoicing'&&<><div className="card invoiceprocess"><div className="reporthead"><div><h2>Facturatieproces</h2><p>Selecteer nog niet gefactureerde uren en markeer deze gezamenlijk als gefactureerd.</p></div></div><div className="formgrid"><Field label="Factuurdatum *"><input type="date" value={invoiceDate} onChange={e=>setInvoiceDate(e.target.value)}/></Field><Field label="Factuurreferentie"><input value={invoiceReference} onChange={e=>setInvoiceReference(e.target.value)} placeholder="Bijvoorbeeld INV-2026-001"/></Field></div><div className="invoicebar"><label><input type="checkbox" checked={unbilled.length>0&&invoiceSelected.length===unbilled.length} onChange={e=>setInvoiceSelected(e.target.checked?unbilled.map(x=>x.id):[])}/> Alles selecteren</label><strong>{invoiceSelected.length} regel(s) geselecteerd</strong><Button onClick={runInvoice} disabled={!invoiceSelected.length}><CheckCircle2 size={17}/> Markeer als gefactureerd</Button></div></div><div className="tablewrap"><table><thead><tr>{['Selectie','Datum','Medewerker','Project','Van-tot','Uren','Waarde'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{unbilled.map(e=>{const p=byId[e.projectId];return <tr key={e.id}><td><input type="checkbox" checked={invoiceSelected.includes(e.id)} onChange={x=>setInvoiceSelected(v=>x.target.checked?[...v,e.id]:v.filter(id=>id!==e.id))}/></td><td>{date(e.date)}</td><td>{e.employee}</td><td>{p?.name}</td><td>{e.startTime}-{e.endTime}</td><td><b>{hours(e.hours)}</b></td><td>{money(e.hours*(p?.hourlyRate||0))}</td></tr>})}</tbody></table>{!unbilled.length&&<div className="empty">Er zijn geen factureerbare uren meer om te verwerken.</div>}</div></>}
 {view==='reports'&&<><div className="metrics three"><Metric label="Budgeturen" value={hours(budget)}/><Metric label="Geboekte uren" value={hours(total)}/><Metric label="Resterende uren" value={hours(budget-total)}/></div><div className="card"><div className="reporthead"><div><h2>Rapportage per medewerker</h2><p>Totalen voor geregistreerde uren en waarde</p></div><div><Button className="secondary" onClick={exportCsv}><Download size={17}/> CSV</Button> <Button className="secondary" onClick={()=>download('projecturen-backup.json',JSON.stringify({projects,employees,entries},null,2),'application/json')}><FileJson size={17}/> Back-up</Button></div></div>{[...new Set(entries.map(e=>e.employee))].map(emp=>{const own=entries.filter(e=>e.employee===emp),h=own.reduce((s,e)=>s+e.hours,0),v=own.reduce((s,e)=>s+(e.billable?e.hours*(byId[e.projectId]?.hourlyRate||0):0),0);return <div className="employee" key={emp}><b><Users size={17}/>{emp}</b><span>{hours(h)}</span><strong>{money(v)}</strong></div>})}</div></>}
 </section></main>{projectOpen&&<Modal title={projectEdit?'Project bewerken':'Nieuw project'} onClose={()=>setProjectOpen(false)}><ProjectForm initial={projectEdit} onSave={saveProject} onCancel={()=>setProjectOpen(false)}/></Modal>}{employeeOpen&&<Modal title={employeeEdit?'Medewerker bewerken':'Nieuwe medewerker'} onClose={()=>setEmployeeOpen(false)}><EmployeeForm initial={employeeEdit} onSave={saveEmployee} onCancel={()=>setEmployeeOpen(false)}/></Modal>}{timeOpen&&<Modal title={timeEdit?'Urenboeking bewerken':'Uren schrijven'} onClose={()=>setTimeOpen(false)}><TimeForm projects={projects} employees={employees} initial={timeEdit} onSave={saveEntry} onCancel={()=>setTimeOpen(false)}/></Modal>}{toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}</div>;
}
function Toolbar({search,setSearch,children}){return <div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Zoeken op project, medewerker of activiteit..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div>{children}</div></div>}
function Metric({label,value,sub,icon}){return <div className="card metric"><div><small>{label}</small><strong>{value}</strong>{sub&&<small className="metricSub">{sub}</small>}</div>{icon&&<span>{icon}</span>}</div>}
